spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  jwt:
    secret: 0123456789abcdef0123456789abcdef
  security:
    public-paths:
      - /auth-service/auth/**
      - /actuator/**
    admin-paths:
      - /user-service/users/admin/**