server:
  port: 8181

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

app:
  jwt:
    secret: 0123456789abcdef0123456789abcdef
  security:
    public-paths:
      - /auth-service/auth/**
      - /actuator/**
    admin-paths:
      - /user-service/users/admin/**